# Generated by Django 3.1 on 2022-03-28 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compName', models.CharField(max_length=225)),
                ('emailTemplate', models.TextField()),
                ('smsTemplate', models.TextField()),
                ('createDate', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodName', models.CharField(max_length=255)),
                ('prodDesc', models.TextField(blank=True)),
                ('prodImage', models.ImageField(upload_to='Images/')),
                ('prodCharge', models.IntegerField()),
                ('preoderAmount', models.IntegerField()),
                ('createDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.company')),
            ],
        ),
    ]
