# Generated by Django 3.1 on 2022-03-28 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preoderFName', models.CharField(max_length=225)),
                ('preoderLName', models.CharField(max_length=255)),
                ('preoderEmail', models.EmailField(max_length=225)),
                ('preoderPhoneNum', models.CharField(max_length=80)),
                ('preoderDate', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
